const {test}=require('node:test'),assert=require('node:assert/strict');
const P=require('../assets/personal-core.js'),C=require('../assets/study-core.js');
function card(meaning='可信的',contexts=[]){return {id:P.cardId('credible',meaning),lemma:'credible',word:'credible',meaning,common:meaning,ipa:'',ipaLabel:'词典原音标',targetId:'',forms:['credible'],contexts,createdAt:1,updatedAt:2};}
function context(example='It is credible.',translation=''){return {example,translation,section_id:'2018-t1',section_title:'2018',source_group:'2018 英语（一）',location:'第1段',kind:'passage',sourceUrl:'exams/2018.html#p1'};}
test('重复收词合并例句且顺序稳定，重复导入不增加数量',()=>{const a=card('可信的',[context()]),b=card('可信的',[context('A credible report.')]);const merged=P.mergeCards([a],[b]);assert.equal(merged.length,1);assert.equal(merged[0].contexts.length,2);assert.equal(merged[0].contexts[0].example,'It is credible.');assert.deepEqual(P.mergeCards(merged,[b]),merged);});
test('相同原形的不同词义使用独立学习编号',()=>{assert.notEqual(card().id,card('可靠的').id);assert.equal(P.mergeCards([card()],[card('可靠的')]).length,2);});
test('旧备份缺少个人词库时保留已有个人词和记录',()=>{const state={...C.emptyState(),personal:[card()]};const old={schema:1,project:C.PROJECT,events:[],settings:{dailyNew:10}};assert.deepEqual(C.mergeBackup(state,old).personal,state.personal);});
test('导出结构可在空状态恢复个人词库和进度',()=>{const backup={...C.emptyState(),personal:[card()],events:[{id:'a',unitId:card().id,at:100,kind:'answer',direction:'en-zh',result:'wrong',hinted:false,contextIndex:0}]};const restored=C.mergeBackup(C.emptyState(),backup);assert.equal(restored.personal[0].id,card().id);assert.equal(C.fold(restored.events)[card().id].status,'unknown');});
test('非法链接和伪造编号整批拒绝，原始数据保持完整',()=>{const a=card('可信的',[context()]),before=JSON.stringify(a),bad=card('可靠的',[{...context(),sourceUrl:'javascript:alert(1)'}]);assert.throws(()=>P.mergeCards([a],[bad]));assert.equal(JSON.stringify(a),before);assert.throws(()=>P.validateCard({...a,id:'forged'}));});
test('超额例句不能静默丢弃，原词条保持不变',()=>{const a=card('可信的',Array.from({length:30},(_,i)=>context('Sentence '+i)));assert.throws(()=>P.mergeCards([a],[card('可信的',[context('Extra sentence')])]));assert.equal(a.contexts.length,30);});
test('补充译文只填空，保留先前已编辑内容',()=>{const a=card('可信的',[context()]),b=card('可信的',[context(undefined,'可信。')]);const merged=P.mergeCards([a],[b]);assert.equal(merged[0].contexts[0].translation,'可信。');assert.equal(a.contexts[0].translation,'');assert.equal(P.mergeCards(merged,[card('可信的',[context(undefined,'另一译文')])])[0].contexts[0].translation,'可信。');});
test('未核对词性使用双向翻卡，不从个人词库拼凑干扰项',()=>{const unit={...card(),pos:'unreviewed'};assert.equal(C.makeQuestion(unit,[unit],'en-zh').mode,'flip');assert.equal(C.makeQuestion(unit,[unit],'zh-en').mode,'flip');});
