/* 固定时间验证学习规则，避免以真实日期碰运气。 */
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../assets/study-core.js');
const t=+new Date(2026,8,16,10),day=C.DAY;
let seq=0;
const answer=(offset,direction='en-zh',result='known',extra={})=>C.validateEvent({id:'e-'+(++seq),unitId:'word-1',at:t+offset,kind:'answer',direction,result,hinted:false,contextIndex:0,...extra});
const state=events=>C.fold(events)['word-1'];
test('初次正确为模糊，次日到期',()=>{const s=state([answer(0)]);assert.equal(s.status,'fuzzy');assert.equal(s.due,t+day)});
test('同一天两个方向不升级，次日可升级',()=>{const es=[answer(0),answer(1000,'zh-en')];assert.equal(state(es).status,'fuzzy');es.push(answer(day,'en-zh'));assert.equal(state(es).status,'familiar');assert.equal(state(es).due,t+4*day)});
test('熟悉后依次按3、7、14、30、60天间隔推进',()=>{let es=[answer(0),answer(day,'zh-en')],at=day;for(const days of [3,7,14,30,60,60]){const s=state(es);assert.equal(s.due,t+at+days*day);at+=days*day;es.push(answer(at,s.lastDirection==='en-zh'?'zh-en':'en-zh'));}});
test('熟悉词提前答对不延长间隔',()=>{const es=[answer(0),answer(day,'zh-en')];const before=state(es);es.push(answer(day+1000));assert.equal(state(es).due,before.due);assert.equal(state(es).step,0)});
test('模糊词提前练习不会推迟到期',()=>assert.equal(state([answer(0),answer(1000,'zh-en')]).due,t+day));
test('提示后确认知道仍为模糊，清除成功凭据',()=>{const s=state([answer(0),answer(day,'zh-en','known',{hinted:true})]);assert.equal(s.status,'fuzzy');assert.deepEqual(s.proofs,{})});
test('猜对不算熟悉',()=>assert.equal(state([answer(0),answer(day,'zh-en','uncertain')]).status,'fuzzy'));
test('答错降级并10分钟后到期',()=>{const s=state([answer(0),answer(day,'zh-en'),answer(2*day,'en-zh','wrong')]);assert.equal(s.status,'unknown');assert.equal(s.due,t+2*day+600000);assert.equal(s.step,-1)});
test('同日纠错仅到模糊',()=>assert.equal(state([answer(0,'en-zh','wrong'),answer(1000),answer(2000,'zh-en')]).status,'fuzzy'));
test('支持手工降级，不允许升级',()=>{const es=[answer(0),answer(day,'zh-en')];es.push(C.validateEvent({id:'d-1',unitId:'word-1',at:t+day+1,kind:'downgrade',level:'unknown'}));es.push({id:'d-2',unitId:'word-1',at:t+day+2,kind:'downgrade',level:'fuzzy'});assert.equal(state(es).status,'unknown')});
test('同样事件乱序重放结果一致',()=>{const es=[answer(0),answer(day,'zh-en'),answer(4*day)];assert.deepEqual(state(es),state([...es].reverse()))});
const units=Array.from({length:6},(_,i)=>({id:'word-'+(i+1),contexts:[{section_id:'s'}]}));
test('今日计划先到期再新词，并扣除今日已学',()=>{const es=[answer(-day),answer(0,'en-zh','wrong',{unitId:'word-2'})];assert.deepEqual(C.plan(units,es,'today','',2,t),['word-1','word-3']);assert.deepEqual(C.plan(units,es,'review','',2,t),['word-1'])});
test('其他词库的备份记录不占每日配额',()=>assert.equal(C.plan(units,[answer(0,'en-zh','known',{unitId:'missing'})],'today','',2,t).length,2));
test('文章练习包括未到期词；按文章过滤',()=>{assert.deepEqual(C.plan(units,[answer(0)],'article','s',1,t),['word-1']);assert.deepEqual(C.plan(units,[],'article','other',10,t),[])});
test('备份合并保留历史、重复导入幂等',()=>{const e=answer(0),backup={...C.emptyState(),events:[e]};let local=C.emptyState();local.events=[answer(day,'zh-en')];const merged=C.mergeBackup(local,backup);assert.equal(merged.events.length,2);assert.equal(C.mergeBackup(merged,backup).events.length,2);assert.equal(local.events.length,1)});
test('异常备份整批拒绝，不部分覆盖',()=>{const local=C.emptyState();assert.throws(()=>C.mergeBackup(local,{...local,events:[answer(0),{id:'bad'}]}));assert.equal(local.events.length,0);assert.throws(()=>C.validateBackup({...local,settings:{dailyNew:0}}));assert.throws(()=>C.validateBackup({...local,project:'other'}))});
test('同一编号不同内容拒绝',()=>{const e=answer(0),local={...C.emptyState(),events:[e]};assert.throws(()=>C.mergeBackup(local,{...local,events:[{...e,result:'wrong'}]}))});
test('拒绝恶意特殊记录编号',()=>assert.throws(()=>answer(0,'en-zh','known',{unitId:'__proto__'})));
test('未审核词与不足干扰项使用翻卡',()=>{const u={id:'u',pos:'unreviewed',gloss:'测试'};assert.equal(C.makeQuestion(u,[],'en-zh').mode,'flip');assert.equal(C.makeQuestion({...u,pos:'n.',word:'test',lemma:'test',exclude:[]},[],'zh-en').mode,'flip')});
const fs=require('node:fs'),vm=require('node:vm'),sandbox={window:{}};vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../output/study-data.js'),'utf8'),sandbox);
test('全词库双向题目均有唯一正确项和互异选项',()=>{const all=sandbox.window.VOCAB_STUDY.units;for(const u of all)for(const d of ['en-zh','zh-en'])for(let round=0;round<20;round++){const q=C.makeQuestion(u,all,d);if(q.mode==='flip')continue;assert.equal(q.options.length,4);assert.equal(q.options.filter(x=>x.id===u.id).length,1);assert.equal(new Set(q.options.map(x=>x.text.toLowerCase())).size,4);assert.ok(q.options.every(x=>x.id===u.id||!u.exclude.includes(x.id)));}});
